name: CI - Projeto Selenide

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]
  workflow_dispatch:

jobs:
  inicio:
    runs-on: ubuntu-latest

    steps:

    - name: ✨ Clonar o código na maquina virtual
      uses: actions/checkout@v4

    - name: ☕ Configurar o Java 23
      uses: actions/setup-java@v4
      with:
          distribution: 'temurin'
          java-version: '23'

    - name: 📦 Instalar dependências e executar testes
      run: mvn clean test

